### ISSUE TITLE
how to use  extra_parameters

### ISSUE THREAD

**Issue by g4b1s** [augustohp/ansible-role-apache#9]
could you please write an example ?
in readme you just mention the existence, but no give an example

**Comment by augustohp** [comment]
As [seen in the template file for vhosts][1]:

```yml
apache_vhosts:
    - servername: my.domain.com
      documentroot: /var/www
      ports: [80, 8080]
      extra_parameters:
          AnApacheParameter: AParameterValue
          AnotherApacheParameter: AnotherParameterValue
```

Let me know if this helps you. If you can create a PR, it would be awesome. :tada:
[1]: https://github.com/augustohp/ansible-role-apache/blob/master/templates/vhosts.conf.j2
